### ISSUE TITLE
[Idea] Laps data usage from Ergast

### ISSUE THREAD

**Issue by siddharth-tewari** [JoniHama/F1QualifyingVersus#1]
Hello, I have a idea for a separate topic from qualifying.
Using the following link I made this excel csv manually.
<a href="http://ergast.com/api/f1/2021/1/laps?limit=1000&offset=0">http://ergast.com/api/f1/2021/1/laps?limit=1000&offset=0</a>
<img src="https://user-images.githubusercontent.com/76590952/149898817-7f0107f8-6112-4349-9231-9cfe44d15094.jpg">
Can you help developing a program which can generate something like this. I tried but failed as quite new to python.
I use it sometimes to make videos on youtube this this.
<a href="https://www.youtube.com/watch?v=oBwat_aOlaA">https://www.youtube.com/watch?v=oBwat_aOlaA</a>

**Comment by JoniHama** [comment]
Sorry for a late response.

While your idea sounds good, I have to decline. This project was my personal project and I wrote it for qualifying data only.  And at the moment I have no interest in starting new Formula 1 related projects.

Still, I believe that if that program is your passion you can overcome the difficulties of Python. It's a good motivator!
Best of luck for your project!
